/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n2.7-dev-3085-gd5fcca8"
#endif /* AVUTIL_FFVERSION_H */
